name: "node0"
nodes:
  node0:
    host: '127.0.0.1'
    port: 8086
    cli-port: 8051
  node1:
    host: '127.0.0.1'
    port: 8087
    cli-port: 8052
  node2:
    host: '127.0.0.1'
    port: 8088
    cli-port: 8053
  node3:
    host: '127.0.0.1'
    port: 8089
    cli-port: 8054

sqlite:
  filename: 'node0.db'
  initfile: 'node0-init.sql'
